const nodemailer = require("nodemailer");

class Email {
  constructor(recipient, subject, text_message, html_message) {
    this.transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: "gpaelevator01@gmail.com",
        pass: "zkshgzbaumskjbyf",
      },
    });
    this.message_header =
      "<div style='background-color: #0088cc; padding: 100px 0px;'><div style='background-color: #ffffff; max-width: 600px; margin: auto; padding: 20px;'>";
    this.message_footer =
      "</div>" +
      '  <div style="width: 600px; margin: auto; background-color: #333f3c; padding: 20px; color: #cbcbcb; font-weight: 200; font-size: 12px; box-shadow: 0px 47px 26px -15px #000000b3;">' +
      "      <p style='width: 100%; text-align: center; margin: 0px;'>This email is autogenerated. Please do not reply</p>" +
      "      <div style='text-align: center;'><a style='color: #0088cc' href='http://www.gpa-elevator.com/' target='_blank'>gpa-elavator.com</a></div>" +
      "  </div>";
    ("+</div>");

    this.mailOptions = {
      from: "admin@gpa-elevator.com",
      to: recipient,
      subject: subject,
      text: text_message,
      html: this.message_header + html_message + this.message_footer,
    };
  }
  async sendEmail() {
    try {
   
      this.transporter.sendMail(this.mailOptions);
    } catch (err) {
      console.log("error sending email", err);
      new AppError("failed to send email", 403);
    }
  }
}

module.exports = Email;
